id: A342BFAF5
title: A Daily Practice of Vajraṇakhī
type: translation
pechas:
- I80F92490
- I2B69EB64
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:25.754980
  last_modified_at: 2023-01-04 11:50:25.754990
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I80F92490/870E: '4887'
  I2B69EB64/B954: '4887'
